name: ChestShop
version: ${project.version}
main: me.moru3.chestshop.ChestShop
api-version: 1.16
authors: [ moru3 ]
description: Create a great shop with chests!
load: STARTUP
permissions:
  chestshop.adminshop:
    default: op
  chestshop.reload:
    default: op
  chestshop.revenue.view:
    default: op
  chestshop.revenue.get:
    default: op
softdepend:
  - Vault
commands:
  chestshop:
    aliases:
      - cs